import type { DownloadRelease } from './release-model';
const escape = (value: string) => value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export function renderPage(release: DownloadRelease): string {
 const v=escape(release.version),dmg=escape(release.dmg.url),zip=escape(release.zip.url);
 return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="RecordReady — 为口播准备的 Mac 录制工具。Screen recording, ready when you are."><title>RecordReady · 准备好，开始录制</title><link rel="stylesheet" href="/style.css"></head>
<body><header><a class="brand" href="/" aria-label="RecordReady 首页"><span class="mark" aria-hidden="true"></span>RecordReady</a><nav aria-label="Language"><a href="#zh" lang="zh-CN">中文</a><span>/</span><a href="#en" lang="en">English</a></nav></header>
<main><section id="zh" lang="zh-CN"><p class="eyebrow">为 MAC 而生 · 公开内测</p><h1>准备好，<br>开始录制<span class="dot">。</span></h1><p class="intro">稿件、画面、镜头，各就各位。<br>让下一次口播，从容开始。</p><div class="download"><a class="button" href="${dmg}">下载 macOS 版 <span aria-hidden="true">↓</span></a><p>Apple Silicon · macOS ${escape(release.minMacOS)}+<br>${v} · 构建 ${release.build}</p></div>
<div class="features"><article><span>01</span><h2>稿件在眼前</h2><p>独立提词区，让表达保持连贯。</p></article><article><span>02</span><h2>画面由你定</h2><p>固定录制区域，只呈现你想分享的内容。</p></article><article><span>03</span><h2>原片留给创作</h2><p>屏幕与摄像头分别保存，方便后期编辑。</p></article></div>
<div class="installation"><h2>第一次安装</h2><ol><li>打开 DMG，将 RecordReady 拖入 Applications。</li><li>当前为 ad-hoc 签名内测版，尚未经过 Apple 公证。如 macOS 阻止打开，请在“系统设置 → 隐私与安全性”确认来源后选择“仍要打开”。</li><li>按需授权屏幕录制、麦克风和摄像头。升级后系统可能要求重新授权。</li></ol><p>应用会检查新版本；下载和重启安装由你确认。录制与保存期间不会安装更新。</p></div></section>
<section id="en" lang="en"><p class="eyebrow">MADE FOR MAC · PUBLIC BETA</p><h2 class="english-title">Ready when you are.</h2><p class="intro">Your script, screen and camera, in place.<br>A calmer start to your next recording.</p><a class="button secondary" href="${dmg}">Download for macOS <span aria-hidden="true">↓</span></a><p class="muted">Apple Silicon · macOS ${escape(release.minMacOS)}+ · ${v}</p><div class="installation"><h3>First installation</h3><ol><li>Open the DMG and drag RecordReady into Applications.</li><li>This beta is ad-hoc signed and has not been notarized by Apple. If macOS blocks launch, verify the source and use System Settings → Privacy &amp; Security → Open Anyway.</li><li>Allow screen recording, microphone and camera access as needed. macOS may ask for permissions again after an update.</li></ol><p>The app checks for updates. You confirm the download and restart to install; recording and saving block installation.</p></div></section>
<section class="release"><h2>版本说明 <span lang="en">/ Release notes</span></h2><p>${escape(release.notes['zh-CN'])}</p><p lang="en">${escape(release.notes['en-US'])}</p><div class="links"><a href="${zip}">完整 ZIP / Full ZIP</a><a href="/releases/${v}/SHA256SUMS.txt">SHA-256 校验 / Checksums</a><a href="/releases/${v}/release.json">发布记录 / Manifest</a></div><details><summary>DMG SHA-256</summary><code>${escape(release.dmg.sha256)}</code></details></section></main><footer>RecordReady <span>少一点准备，多一点表达。 / Less setup. More expression.</span></footer></body></html>\n`;
}
