import {readFileSync,writeFileSync,statSync} from 'node:fs';import {join,resolve} from 'node:path';import {createHash,randomUUID} from 'node:crypto';import {execFileSync} from 'node:child_process';import {verifyRelease,installerName} from './update-manifest.mjs';
const version=process.argv[2],name=installerName(version),folder=resolve(import.meta.dirname,'release/published',version),config=JSON.parse(readFileSync(join(import.meta.dirname,'resources/update-config.json'))),release=verifyRelease(readFileSync(join(folder,'release.json'),'utf8'),config.publicKey);
if(release.version!==version)throw Error('release_version_mismatch');const data=readFileSync(join(folder,name));if(data.length!==release.file.size||createHash('sha512').update(data).digest('base64')!==release.file.sha512)throw Error('release_hash_mismatch');
const sha=createHash('sha256').update(data).digest('hex'),url=`/releases/windows/${version}/${name}`;
writeFileSync(join(folder,'index.html'),`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RecordReady · Windows 内测版</title><link rel="stylesheet" href="/style.css"></head><body><header><a class="brand" href="/">RecordReady</a><a href="/">macOS</a></header><main><p class="eyebrow">WINDOWS · 内测 / BETA</p><h1>准备好，<br>开始录制。</h1><p class="intro">屏幕与摄像头独立 MP4，提词、暂停与继续。<br>Screen and camera recordings, with a teleprompter.</p><div class="download"><a class="button" href="${url}">下载 Windows 版 / Download ↓</a><p>Windows 10 22H2 / 11 · x64<br>${version} · ${(release.file.size/1024/1024).toFixed(1)} MB</p></div><section class="installation"><h2>安装与更新 / Installation &amp; updates</h2><p>运行安装程序，按向导为当前用户安装。此内测包尚无 Authenticode 发布者签名，Windows 可能显示来源提示。Windows 10 22H2 已实测；Windows 11 尚待验证。</p><p>在设置中检查更新，确认下载后可选择“重启安装”。录制、暂停和保存期间禁止安装。更新保留设置和录像；增量不可用时自动下载完整包。</p><p>Run the installer for your current account. This beta has no Authenticode publisher certificate. Tested on Windows 10 22H2; Windows 11 testing is pending. Use Settings to check, download, then restart to install. Updates retain settings and recordings; recording and saving block installation.</p><p>摄像头预览右键可切换镜像、形状和铺满。Windows 版暂不提供 macOS 原生美颜。录制使用可变帧率；4K 竖屏在部分设备上帧率偏低，尚未完成 4K 30fps 验收。</p></section><section class="release"><h2>SHA-256</h2><code>${sha}</code><p><a href="/releases/windows/${version}/inventory.json">发布记录 / Release record</a></p></section></main></body></html>`);
const files={};for(const file of [name,name+'.blockmap','release.json','inventory.json','index.html']){const bytes=readFileSync(join(folder,file));files[file]={bytes:statSync(join(folder,file)).size,sha256:createHash('sha256').update(bytes).digest('hex')};}
if(process.argv.includes('--prepare-only')){console.log(JSON.stringify({version,folder,files}));process.exit(0);}
const identity=process.env.RECORDREADY_SSH_IDENTITY,known=process.env.RECORDREADY_SSH_KNOWN_HOSTS;if(!identity||!known)throw Error('Set RECORDREADY_SSH_IDENTITY and RECORDREADY_SSH_KNOWN_HOSTS');const target='root@39.96.16.242',id=randomUUID(),stage=`/srv/recordready/staging/${id}`,args=['-i',identity,'-o','BatchMode=yes','-o','StrictHostKeyChecking=yes','-o',`UserKnownHostsFile=${known}`,'-o','ConnectTimeout=15'];const ssh=(command,input)=>execFileSync('ssh',[...args,target,command],{input,stdio:input?['pipe','inherit','inherit']:'inherit'});
ssh('mkdir /srv/recordready/deploy.lock');try{ssh(`mkdir -p ${stage}`);execFileSync('scp',[...args,...Object.keys(files).map(file=>join(folder,file)),`${target}:${stage}/`],{stdio:'inherit'});const source=readFileSync(resolve(import.meta.dirname,'../../..','scripts/release/deploy-windows-remote.py'),'utf8'),payload=Buffer.from(JSON.stringify({id,version,files})).toString('base64');ssh('python3 -',source.replace("json.load(sys.stdin)",`json.loads(base64.b64decode('${payload}'))`));}finally{ssh('rmdir /srv/recordready/deploy.lock');}
