import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {RecordingFiles} from '../recording-files.mjs';
const box=type=>{const b=Buffer.alloc(12);b.writeUInt32BE(12);b.write(type,4);return b;};const valid=Buffer.concat(['ftyp','moov','mdat'].map(box));
const root=resolve(import.meta.dirname,'../.validation/files');await mkdir(root,{recursive:true});
test('ordered chunk writes persist before atomic promotion',async()=>{const directory=await mkdtemp(join(root,'ordered-')),files=new RecordingFiles(directory);await files.create(['screen']);await Promise.all([files.write('screen',valid.subarray(0,12)),files.write('screen',valid.subarray(12))]);assert.deepEqual(await files.finish(['screen']),{screen:'saved'});assert.deepEqual(await readFile(join(directory,'screen.mp4')),valid);});
test('write failure preserves healthy stream and failed partial file',async()=>{const directory=await mkdtemp(join(root,'partial-')),files=new RecordingFiles(directory);await files.create(['screen','camera']);await files.write('screen',valid);files.files.get('camera').handle.write=async()=>{throw Error('ENOSPC')};await assert.rejects(files.write('camera',Buffer.from('failed')),/ENOSPC/);const result=await files.finish(['screen','camera']);assert.equal(result.screen,'saved');assert.equal(result.camera,'ENOSPC');assert.deepEqual(await readFile(join(directory,'screen.mp4')),valid);assert.equal((await readFile(join(directory,'camera.partial.mp4'))).length,0);});
test('existing partial is never overwritten and empty output never reports success',async()=>{const directory=await mkdtemp(join(root,'existing-'));await writeFile(join(directory,'screen.partial.mp4'),'keep');await assert.rejects(new RecordingFiles(directory).create(['screen']),/EEXIST/);assert.equal(await readFile(join(directory,'screen.partial.mp4'),'utf8'),'keep');const files=new RecordingFiles(directory);await files.create(['camera']);assert.equal((await files.finish(['camera'])).camera,'incomplete_recording');});
test('promotion never overwrites an existing finished recording',async()=>{const directory=await mkdtemp(join(root,'finished-')),files=new RecordingFiles(directory);await files.create(['screen']);await files.write('screen',valid);await writeFile(join(directory,'screen.mp4'),'original');assert.match((await files.finish(['screen'])).screen,/EEXIST/);assert.equal(await readFile(join(directory,'screen.mp4'),'utf8'),'original');assert.deepEqual(await readFile(join(directory,'screen.partial.mp4')),valid);});

test('encoder header without media never becomes a finished MP4',async()=>{const directory=await mkdtemp(join(root,'header-')),files=new RecordingFiles(directory);await files.create(['screen']);await files.write('screen',box('ftyp'));assert.equal((await files.finish(['screen'])).screen,'incomplete_mp4');assert.deepEqual(await readFile(join(directory,'screen.partial.mp4')),box('ftyp'));});
test('truncated media box is rejected and retained',async()=>{const directory=await mkdtemp(join(root,'truncated-')),files=new RecordingFiles(directory);await files.create(['screen']);await files.write('screen',valid.subarray(0,-1));assert.equal((await files.finish(['screen'])).screen,'truncated_mp4');});
