import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';import {join,resolve} from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
const root=resolve(import.meta.dirname,'../.validation/updater-tests');mkdirSync(root,{recursive:true});const folder=mkdtempSync(join(root,'run-')),installer=join(folder,'setup.exe'),payload=Buffer.from('test fixture, not an executable');writeFileSync(installer,payload);writeFileSync(join(folder,'update-config.json'),JSON.stringify({feedUrl:'https://recordready.qiushui.me/updates/windows/x64/release.json',publicKey:'A'.repeat(43)+'='}));process.resourcesPath=folder;
globalThis.rrGateTest={folder,installer,info:{version:'0.1.0-windows.2',files:[{size:payload.length,sha512:createHash('sha512').update(payload).digest('base64')}]},confirm:async()=>({response:0}),download:async()=>[installer],cancelled:false};
const modules={
 electron:`exports.app={getVersion:()=>"0.1.0-windows.1",getPath:()=>globalThis.rrGateTest.folder,quit:()=>{throw Error("unexpected quit")}};exports.dialog={showMessageBox:()=>globalThis.rrGateTest.confirm()};`,
 'electron-updater/out/NsisUpdater.js':`const {EventEmitter}=require('node:events');exports.NsisUpdater=class extends EventEmitter{setFeedURL(){}async checkForUpdates(){return {isUpdateAvailable:true,updateInfo:globalThis.rrGateTest.info,cancellationToken:{cancel(){globalThis.rrGateTest.cancelled=true}}}}async downloadUpdate(){return globalThis.rrGateTest.download()}};`,
 'electron-updater/out/providers/Provider.js':`exports.Provider=class {};`,
};
await build({entryPoints:[resolve(import.meta.dirname,'../updater.mjs')],outfile:join(folder,'updater.cjs'),bundle:true,platform:'node',format:'cjs',plugins:[{name:'transport-fixtures',setup(b){b.onResolve({filter:/^electron(?:$|-updater\/)/},args=>({path:args.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},args=>({contents:modules[args.path],loader:'js'}));}}]});
const {createUpdater}=createRequire(import.meta.url)(join(folder,'updater.cjs'));
const tick=()=>new Promise(resolve=>setTimeout(resolve,10));
async function ready(busy){globalThis.rrGateTest.download=async()=>[installer];writeFileSync(installer,payload);const updater=createUpdater({busy,allowExit:()=>assert.fail('must not exit'),language:()=> 'en',log:()=>{}});await updater.operation('check');while(updater.snapshot().phase==='checking')await tick();assert.equal(updater.snapshot().phase,'available');await updater.operation('download');while(['downloading','preparing'].includes(updater.snapshot().phase))await tick();assert.equal(updater.snapshot().phase,'ready');return updater;}
test('busy recording blocks installation before any confirmation',async()=>{let prompts=0;globalThis.rrGateTest.confirm=async()=>{prompts++;return {response:1}};const updater=await ready(()=>true);await assert.rejects(updater.operation('install'),/session_busy/);assert.equal(prompts,0);assert.equal(updater.snapshot().phase,'ready');});
test('recording that starts during confirmation blocks installation again',async()=>{let busy=false,answer;globalThis.rrGateTest.confirm=()=>new Promise(resolve=>answer=resolve);const updater=await ready(()=>busy),install=updater.operation('install');while(!answer)await tick();busy=true;answer({response:1});await assert.rejects(install,/session_busy/);assert.equal(updater.snapshot().phase,'ready');});
test('cancelled confirmation keeps the verified payload ready',async()=>{globalThis.rrGateTest.confirm=async()=>({response:0});const updater=await ready(()=>false);await updater.operation('install');assert.equal(updater.snapshot().phase,'ready');});
test('confirmation and handoff cannot be invalidated by concurrent update commands',async()=>{let answer;globalThis.rrGateTest.confirm=()=>new Promise(resolve=>answer=resolve);const updater=await ready(()=>false),install=updater.operation('install');while(!answer)await tick();await assert.rejects(updater.operation('cancel'),/update_busy/);await assert.rejects(updater.operation('check'),/update_busy/);assert.equal((await updater.operation('status')).phase,'ready');answer({response:0});await install;assert.equal(updater.snapshot().phase,'ready');});
test('installer tampering is rejected again before handoff',async()=>{globalThis.rrGateTest.confirm=async()=>({response:1});const updater=await ready(()=>false);writeFileSync(installer,'changed');await assert.rejects(updater.operation('install'),/installer_size_mismatch/);assert.equal(updater.snapshot().phase,'ready');});
test('cancel revokes late download completion and never silently installs',async()=>{const updater=await ready(()=>false);await updater.operation('check');while(updater.snapshot().phase==='checking')await tick();let finish;globalThis.rrGateTest.download=()=>new Promise(resolve=>finish=resolve);await updater.operation('download');await updater.operation('cancel');assert(globalThis.rrGateTest.cancelled);finish([installer]);await tick();assert.equal(updater.snapshot().phase,'idle');});
